### ISSUE TITLE
Question about emulators

### ISSUE THREAD

**Issue by FabioLolix** [luongvo209/Awesome-Linux-Software#312]
Should game emulators and theirs frontend have dedicated section?

Where I should add sdlmame, qmc2 and gnome-video-arcade for example?

**Comment by SaintFenix** [comment]
Being that Games just got a complete re-write, I'd say that making a new "Emulators" section underneath the  "Games" Tag would probably not be a bad idea, especially as the list currently has few if any emulators. I'd gladly throw in a few myself.

**Comment by LewisVo** [comment]
Yeah another subcateogry for that is fine @FabioLolix .

**Comment by SaintFenix** [comment]
put these into my newest pull request, @luongvo209 please close at your convenience.
