### ISSUE TITLE
Cryptocurrency:

### ISSUE THREAD

**Issue by SaintFenix** [luongvo209/Awesome-Linux-Software#325]
I'm interested in hearing what people here would think if I put together a new Cryptocurrency section.

Being that a lot of people are getting exposed to Linux thanks to wanting to mine crypto, and usually that being done on Linux machines. I feel that we would have a pretty good audience here for it.

I figure I'd make it as expansive as possible, with both mining programs, and wallets included.

What does everyone think?

**Comment by LewisVo** [comment]
Could you give me some example items that you would put under that category? @SaintFenix

**Comment by SaintFenix** [comment]
closing for now, will be combined into a larger issue:
