### ISSUE TITLE
rICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARE

### ISSUE THREAD

**Issue by epic8009** [luongvo209/Awesome-Linux-Software#335]
> rICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARE

> 

> 

> 

> rICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARErICHARD STALLMAN: YOU CANT EAT P[ROPRIETARY SOFSFTWARE

**Comment by luongvo209** [comment]
Thank you for your contribution @epic8009. I reported you to Github. I think you should take a new email address or look at possible alternatives like Gitlab or Bitbucket.
