### ISSUE TITLE
Adding "twin" text window environment and terminal multiplexer

### ISSUE THREAD

**Issue by cosmos72** [luongvo209/Awesome-Linux-Software#345]
You may want to consider adding "twin" to the terminals emulators section:

https://github.com/cosmos72/twin - Fast, cross-platform, lightweight text-mode window environment with mouse support. Enables multiple terminals in a single Linux console or X11 graphical window. Works on Linux, Mac OS X and *BSD

(disclaimer: I am the author)

**Comment by SaintFenix** [comment]
I saw your program in a reddit post recently, I think it's really neat. if you were to submit a pull request formatted appropriately to the eng-README, I'm certain it would be accepted.
