### ISSUE TITLE
 I dont know how to use this repo

### ISSUE THREAD

**Issue by liangjiongyao** [luongvo209/Awesome-Linux-Software#366]
system:centos7.5
1.i dont know how to download
2.how to install software
please help me,i am a newbie

**Comment by luongvo209** [comment]
Hello @liangjiongyao , this repo doesn't contain downloading  and installing instructions to softwares. It is just a list of useful softwares. To know how to install each of them on your Linux distro (centos in this case), you need to follow the link and go to each software homepage. Besides, maybe you will need to know how to install software on centos in general : https://www.centos.org/forums/viewtopic.php?t=871

**Comment by liangjiongyao** [comment]
thank you so much! I will check it later






------------------ Original ------------------
