### ISSUE TITLE
tux4kids

### ISSUE THREAD

**Issue by Tilson09** [luongvo209/Awesome-Linux-Software#370]
Not sure if the site just isn't maintained or if it is just still in development but whenever I try to pull the site I receive

 `It works!

This is the default web page for this server.

The web server software is running but no content has been added, yet.`

**Comment by luongvo209** [comment]
Yes thank you @Tilson09 . It is dead. I m removing it now

**Comment by SaintFenix** [comment]
@luongvo209 this has been resolved, and I've removed the remaining tux4kids in my most recent commit. So this can be closed, once the commit has been accepted.
