### ISSUE TITLE
Moving to Gitlab?

### ISSUE THREAD

**Issue by SaintFenix** [luongvo209/Awesome-Linux-Software#375]
#373 

Should the repo be moved to Gitlab to keep everything owned by someone who champions open source?

I'd totally be for a move to Gitlab.

The only thing I'd want to say, is not to delete this repo entirely, but to leave a redirect to the new repo wherever it may be, due to the popularity of this repo on the google rankings, this popularity keeps this list moving and updated.

**Comment by luongvo209** [comment]
@chrunchyjesus  @dyoungwd No Bitbucket is not an open source product.   
But I myself don't care too much whether a product is open-source or not. It's about the product's quality, vision and behaviour that I care about. We have all been using a not-so-open Github for years and it's still fine, mostly because Github is nice, working reliably and showing a great attitude towards other open source projects.   
The fact that Github is acquired by another big player is also fine to me. Github itself as a company has a lot of problems in management and finance. However, what I am concerned about the most is Microsoft. Needless to say they are too famous for being evil.  
So why moving this to Gitlab?   

1. To be less dependent on Github. In the worse scenario like Github turns bad, we don't have to worry.  
2. This project is not so massively active like others. We are not dependent on some Github-specific features and now receiving something like 1-2 PR every week, which makes us suitable for a test drive on Gitlab. 
3. To try Gitlab out, and to inspire people that it is a possible alternative if it really is one. 
4....

That's all I can come up with right now. So what's the risk?
1. Having fewer contributors, maybe!?
2....  

In fact I set up a mirror on gitlab a while ago, before all this happens : https://gitlab.com/luongvo209/Awesome-Linux-Software 

I will leave this open for you guys to share your idea.  
Oh , and btw @SaintFenix , we are not deleting this repo. The transition will be: 
1. Not accepting issues and PRs on Github - notify people that we are moving to Gitlab
2. Archiving this repo.

**Comment by chrunchyjesus** [comment]
@luongvo209 Does that mean you prefer the next few pull requests on Gitlab in order to test it out?

**Comment by SaintFenix** [comment]
I think the steps he's labeled out, would mean that we would test things over there first, perhaps keep making pull requests here, and mirroring them there for awhile, and once that is all going well and we are happy with it, shutting down PRs here.

I'm all for this. I certainly hope to keep contributing when time allows.

**Comment by chrunchyjesus** [comment]
Commits from Gitlab and Github can be synced both ways. There might be no need to mirror pull requests if that is set up.

**Comment by SaintFenix** [comment]
@luongvo209 is our maintainer, if he's game to keep them both in sync, then I have no problem with the "one foot in Github, the other in Gitlab" plan.

**Comment by luongvo209** [comment]
Currently both Github and Gitlab serves us well. I will make a decision this weekends. Please stay tune. <Sorry for not being active in this discussion - I am being chased by deadlines 😢  >

**Comment by Zied-Guesmi** [comment]
Wether you are moving to Gitlab or not I'd personally (If I'm allowed to) recommend keeping this repo actif due to it's history.

**Comment by luongvo209** [comment]
Yes of course I won't delete or do anything harmful to it. Chill, guys 😂

**Comment by luongvo209** [comment]
Guys, I want to announce that this would be delayed a little bit. I am fearing that people would be confused about how to use Gitlab in general because the flow is not that similar over there. Working on a guide (or finding one) to instruct people how to use/migrate to  Gitlab for now.

**Comment by crakoucas** [comment]
Gitlab is houst by Microsoft Azure, the beast is everywhere. But Gitlab say that they will change their houst platform for Google Cloud.

**Comment by luongvo209** [comment]
@chrunchyjesus @SaintFenix and others, could you guy read this and give me some feedback :)   https://github.com/luongvo209/Short-Gitlab-Tutorial

**Comment by chrunchyjesus** [comment]
@luongvo209 The language is a bit casual. Is it intended?

**Comment by luongvo209** [comment]
@chrunchyjesus  Yes it is intended. I used very simple language, considering the fact that contributors of this repo are from different languages. 😄

**Comment by SaintFenix** [comment]
@luongvo209 I could follow that even if I was hammered from being out at a bar for two nights straight. I think it's very straightforward, and well worded. 

Personally I'll still be using Gitkraken and it's gitlab interface so, my workflow won't change too much.

**Comment by chrunchyjesus** [comment]
@luongvo209 Just in case you did not see it coming: I created a [merge request on Gitlab](https://gitlab.com/luongvo209/Awesome-Linux-Software/merge_requests/373). :)

**Comment by luongvo209** [comment]
@chrunchyjesus Yeah I did see it ;) I am cleaning up stuffs here to turn off mirroring on Gitlab and starts working on it seriously

**Comment by SaintFenix** [comment]
So the current plan is this:

**We will operate both Github and Gitlab, and accept merge requests on either, they will remain mirroring each other so that people can contribute on both platforms.**

Should that be the assumption we are running under for now?

**Comment by luongvo209** [comment]
@SaintFenix Hmm, actually no. We are following a plan that I told you above : 
> Oh , and btw @SaintFenix , we are not deleting this repo. The transition will be:
Test things Gitlab
Not accepting issues and PRs on Github - notify people that we are moving to Gitlab
Archiving this repo.

But I am a little busy at this moment so that won't happen until next week. Sorry 😭

**Comment by luongvo209** [comment]
@chrunchyjesus  @SaintFenix and others, I have successfully set up our Gitlab. Please check it out : https://gitlab.com/luongvo209/Awesome-Linux-Software and give me feedbacks here ;)

**Comment by FabioLolix** [comment]
OSS and money icons are not displayed, they are linked to github domains?

A couple of issues can be closed like VCV rack and question about emulators

**Comment by luongvo209** [comment]
Hi @FabioLolix , they are displayed clearly from what I have seeen. The issue sessions are to be worked on ;) 
![image](https://user-images.githubusercontent.com/15828926/42422263-df2244e0-830c-11e8-9b4b-8877dd9e2771.png)

**Comment by FabioLolix** [comment]
Hi, browser issue indeed, on other browsers or private mode is ok

**Comment by luongvo209** [comment]
@FabioLolix I tried on Firefox + Chrome. Everything is fine. Maybe you are using some extensions that block these little images from loading 🤔  (since private mode works)

**Comment by luongvo209** [comment]
BTW, congrats @chrunchyjesus 
![image](https://user-images.githubusercontent.com/15828926/42422382-2f08c37e-830f-11e8-91ce-cb415c4d5d48.png) 
for being the first contributor on Gitlab 😄 🥂 

Oh, also, I set up Github to mirror Gitlab, so you should see things that you mentioned above in the latest commit 👍 
![image](https://user-images.githubusercontent.com/15828926/42422397-64fc5388-830f-11e8-886a-1c10dd572237.png)

**Comment by chrunchyjesus** [comment]
Yay. :)

**Comment by FabioLolix** [comment]
Changed a couple of settings of extenstion Privacy Badger and now is working

**Comment by luongvo209** [comment]
@chrunchyjesus @FabioLolix Good to hear that you guys are seeing functional stuffs 💛 Maybe take a look at Gitlab and play around. I will support you guys with all the questions ;).
- Quick ref: https://github.com/luongvo209/Short-Gitlab-Tutorial

**Comment by luongvo209** [comment]
hello @SaintFenix , I am having a big PR and it touches the games part. Can you help me review this 
 https://gitlab.com/luongvo209/Awesome-Linux-Software/merge_requests/374/diffs

**Comment by luongvo209** [comment]
This move has been reverted due to this issue https://gitlab.com/luongvo209/Awesome-Linux-Software/issues/371 

We are never moving to Gitlab again in the future for this project.
