### ISSUE TITLE
Popcorntime link is actually unsafe fork

### ISSUE THREAD

**Issue by jacklul** [luongvo209/Awesome-Linux-Software#419]
https://www.reddit.com/r/PopCornTime/comments/4kf8lk/popcorn_time_what_is_real_what_is_fake/

The correct domain is **popcorntime.sh**.
The image which shows up everywhere when people ask for official domain: https://i.imgur.com/5s9K3zc.jpg

**Comment by luongvo209** [comment]
Thank you for reporting this issue. I will try to get back after some investigation
