### ISSUE TITLE
Hyperlink of Google Play Music Desktop Player is broken

### ISSUE THREAD

**Issue by ndsvw** [luongvo209/Awesome-Linux-Software#619]
Hyperlink https://www.googleplaymusicdesktopplayer.com/ is broken. It is part of all the Readme files. Has not been reachable in 2022 according to web.archive.org

(This is the last broken one I've found. But there are 2 or 3 https links left with expired certificates in the list. What about them?)

**Comment by FabioLolix** [comment]
Seems safe to remove the program from the list

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3926

https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/issues/3950

btw this is using electron 3, we are at 20

**Comment by ndsvw** [comment]
> If given the time, I could be writing a bot that would run in Github Action that tries to make a http connection to all these links to check their availability

@luong-komorebi Don't reinvent the wheel 😉: https://github.com/gaurav-nelson/github-action-markdown-link-check
